### PR TITLE
help  needs hlp

### PR DESCRIPTION
**Pull request by dewomser**
version can help 😄

### CODE REVIEW

**Comment by daPhipz** [comment]
Great idea! I spotted some inconsistencies though, where it still says "version" and not "help". There may be even more, so have a thorough look 😬

**Comment by bit101** [comment]
I was literally thinking of this exact same idea yesterday. :)
Not convinced of the value of it though, with only `-h` and `--help` as options for almost every program.

Some command line programs do have more complex scenarios for help on specific commands, like `program help command`. (or maybe program command help`?) But I don't think it would be possible to go down that path.

Gotta think some more if I want to add this. Feel free to publish it on your own if you wan though.

**Comment by dewomser** [comment]
Thank you for version . I like your Bash-style
I will now publish hlp for my own on.
In hlp will be always  a link back to version
https://github.com/bit101/version

**Comment by bit101** [comment]
Cool. I'll be happy to link back too.

**Pull request closed without merging**
