### PR TITLE
Add other tools

### PR DESCRIPTION
**Pull request by daPhipz**
Added borg, code, eog, gedit, gitkraken, guake, htop, libreoffice, meld, mpv, nautilus

### CODE REVIEW

**Comment by bit101** [comment]
Thanks for the adds, and the mention on the show!

**Comment by daPhipz** [comment]
You mean Ubuntu Podcast?
I have nothing to do with that show (apart from very much enjoying it, of course :wink:)
But yes, I learned about your project that way ;)

**Comment by bit101** [comment]
Ah, sorry. Martin mentioned he would be adding some stuff to the project. And when I looked at your profile I saw some "wimpysworld" repos listed so I thought you were him. The user name didn't make sense, but you never know! :)

**Comment by daPhipz** [comment]
Haha yeah - I just follow his YouTube channel and contribute bits and
pieces to his projects. If you're interested, check out his Discord server
- it's a very friendly and fun community over there!

Keith Peters <notifications@github.com> schrieb am Sa., 5. Sept. 2020,
03:12:

**Pull request merged**
